name: Run Selenium Tests

# Trigger the pipeline when pushing to the repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use Ubuntu for the runner

    strategy:
      matrix:
        browser: [chrome, firefox]  # Run tests on both Chrome and Firefox

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have all dependencies in requirements.txt

      # Step 4: Install WebDriver Manager dependencies
      - name: Install WebDriver Manager dependencies
        run: |
          pip install webdriver-manager

      # Step 5: Run the tests
      - name: Run tests with pytest
        run: |
          pytest tests/qa_selenium_test.py --browser ${{ matrix.browser }} -v  # Run the tests for the specified browser

      # Step 6: Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-results
          path: test-results/  # Upload the test-results folder
